### ISSUE TITLE
Move clinic codes to KV store

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/go-ndoh#105]
Over 8000 codes now. Should prime the KV store with the clinics we have, then use the API Jembi provided for not found lookups and only fail on those still null.

Also, if text then detect as not a bad number and respond with better error message about the difference between name and code.

**Comment by gsvr** [comment]
@imsickofmaps I'm closing this since we've implemented the change to use Jembi API for clinic code lookup. If the second part of this is still desired let's open a Jira ticket for it and get input on the better error message - there is currently no Jira ticket for this.
