### ISSUE TITLE
Implement subscription duplication prevention

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/go-ndoh#117]
Related: https://praekelt.atlassian.net/browse/NDOH-127

**Comment by smn** [comment]
```
<!---
@huboard:{"order":2.0}
-->
```

?

**Comment by imsickofmaps** [comment]
![screenshot 2014-09-10 15 17 00](https://cloud.githubusercontent.com/assets/1228977/4217915/d34351f0-38ec-11e4-8c9b-647df25a89e1.png)

**Comment by imsickofmaps** [comment]
Fixed in other issues
