### ISSUE TITLE
v1 Metrics - HIE transmits

### ISSUE THREAD

**Issue by gsvr** [praekeltfoundation/go-ndoh#18]
- [ ] Number of completed clinic registrations sent to HIE from Clinic Line - Total and over time
- [ ] Number of complete suspected pregnancy registrations sent to HIE from CHW line - Total and over time
- [ ] Number of complete subscriptions sent to HIE  from the public line - Total and over time

**Comment by imsickofmaps** [comment]
Handled in #32
